### PR TITLE
refs #15217 - puppet 4 support

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ekohl** [comment]
Not sure why it isn't picking up the port.

**Comment by ekohl** [comment]
Oh, port isn't in scope in the template. Should be ```<%= scope['crane::port'] %>```

**Comment by stbenjam** [comment]
> <%= scope['crane::port'] %>

Can we move to scope[]? Or should we still be doing scope.lookupvar?

**Comment by ekohl** [comment]
I think ```scope[]``` is the way to go. The reason theforeman isn't using it is because we used to support a puppet version (2.6?) that didn't have it, but Katello already dropped support for that puppet version.

**Comment by stbenjam** [comment]
Thanks, updated

**Comment by ekohl** [comment]
ACK

**Pull request merged**
